# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Quote' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Quote
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'

  target 'QuoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QuoteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
